# Generated by Django 3.0.5 on 2020-11-14 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_title', models.CharField(max_length=260)),
                ('prod_img', models.ImageField(blank=True, null=True, upload_to='media/products')),
                ('prod_original_price', models.CharField(max_length=20)),
                ('prod_discounted_price', models.CharField(max_length=20)),
                ('prod_desc', models.TextField(max_length=500)),
                ('prod_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categories')),
            ],
        ),
    ]
